---
- name: Converge
  hosts: all
  roles:
    - role: ansible-onepassword-local-lookup-plugin
  tasks:
    - name: generate test file
      template:
        src: testfile.txt.j2
        dest: /testfile.txt
